spring.application.name=coop-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/coopdb
spring.datasource.username=coopuser
spring.datasource.password=cooppass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080